/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package festival;

import java.awt.CardLayout;

/**
 *
 * @author jaleo
 */
public class festival_01 extends javax.swing.JFrame {

    /**
     * Creates new form festival_01
     */
    public festival_01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north = new javax.swing.JPanel();
        north_buttons = new javax.swing.JPanel();
        btn_day1 = new javax.swing.JButton();
        btn_day2 = new javax.swing.JButton();
        btn_day3 = new javax.swing.JButton();
        display = new javax.swing.JLabel();
        center = new javax.swing.JPanel();
        p_general = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p_day1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        p_day2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        p_day3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        south = new javax.swing.JPanel();
        btn_restore = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        north.setLayout(new java.awt.GridLayout(0, 1));

        north_buttons.setLayout(new java.awt.GridLayout(1, 0));

        btn_day1.setText("Día 1");
        btn_day1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_day1ActionPerformed(evt);
            }
        });
        north_buttons.add(btn_day1);

        btn_day2.setText("Día 2");
        btn_day2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_day2ActionPerformed(evt);
            }
        });
        north_buttons.add(btn_day2);

        btn_day3.setText("Día 3");
        btn_day3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_day3ActionPerformed(evt);
            }
        });
        north_buttons.add(btn_day3);

        north.add(north_buttons);

        display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        display.setText("Información general");
        north.add(display);

        getContentPane().add(north, java.awt.BorderLayout.PAGE_START);

        center.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Card 0");
        p_general.add(jLabel1);

        center.add(p_general, "card2");

        jLabel2.setText("Card 1");
        p_day1.add(jLabel2);

        center.add(p_day1, "card3");

        jLabel3.setText("Card 2");
        p_day2.add(jLabel3);

        center.add(p_day2, "card4");

        jLabel4.setText("Card 3");
        p_day3.add(jLabel4);

        center.add(p_day3, "card5");

        getContentPane().add(center, java.awt.BorderLayout.CENTER);

        btn_restore.setText("Restaurar");
        btn_restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restoreActionPerformed(evt);
            }
        });
        south.add(btn_restore);

        btn_exit.setText("Salir");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        south.add(btn_exit);

        getContentPane().add(south, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_day1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_day1ActionPerformed
        ((CardLayout) center.getLayout()).show(center, "card3");
        display.setText("Día 1");
        btn_day1.setEnabled(false);
        btn_day2.setEnabled(true);
        btn_day3.setEnabled(true);
    }//GEN-LAST:event_btn_day1ActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_day2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_day2ActionPerformed
        ((CardLayout) center.getLayout()).show(center, "card4");
        display.setText("Día 2");
        btn_day1.setEnabled(true);
        btn_day2.setEnabled(false);
        btn_day3.setEnabled(true);
    }//GEN-LAST:event_btn_day2ActionPerformed

    private void btn_day3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_day3ActionPerformed
        ((CardLayout) center.getLayout()).show(center, "card5");
        display.setText("Día 3");
        btn_day1.setEnabled(true);
        btn_day2.setEnabled(true);
        btn_day3.setEnabled(false);
    }//GEN-LAST:event_btn_day3ActionPerformed

    private void btn_restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restoreActionPerformed
        ((CardLayout) center.getLayout()).show(center, "card2");
        display.setText("Información general");
        btn_day1.setEnabled(true);
        btn_day2.setEnabled(true);
        btn_day3.setEnabled(true);
    }//GEN-LAST:event_btn_restoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(festival_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(festival_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(festival_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(festival_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new festival_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_day1;
    private javax.swing.JButton btn_day2;
    private javax.swing.JButton btn_day3;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_restore;
    private javax.swing.JPanel center;
    private javax.swing.JLabel display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel north;
    private javax.swing.JPanel north_buttons;
    private javax.swing.JPanel p_day1;
    private javax.swing.JPanel p_day2;
    private javax.swing.JPanel p_day3;
    private javax.swing.JPanel p_general;
    private javax.swing.JPanel south;
    // End of variables declaration//GEN-END:variables
}
